# Generated by Django 4.2.3 on 2023-08-02 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Face_Recognation', '0002_face_recognation2'),
    ]

    operations = [
        migrations.AddField(
            model_name='face_recognation2',
            name='image',
            field=models.ImageField(default=None, upload_to='Face_Recognation/media_image'),
        ),
    ]
