# Generated by Django 4.2.3 on 2023-08-10 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='attendance_record_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('course_name', models.CharField(max_length=50)),
                ('session', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='course_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('verification_code', models.TextField()),
                ('teacher', models.TextField()),
                ('students_list', models.TextField(null=True)),
                ('sessions_list', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='person_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('isStudent', models.BooleanField()),
                ('rollNumber', models.IntegerField()),
                ('courses_list', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='session_record_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('location', models.TextField()),
            ],
        ),
    ]
