# Generated by Django 4.2.3 on 2023-08-10 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance_record_table',
            old_name='student_id',
            new_name='student_Id',
        ),
    ]
