# Generated by Django 4.2.3 on 2023-08-10 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_rename_student_id_attendance_record_table_student_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person_table',
            name='isStudent',
        ),
        migrations.AlterField(
            model_name='person_table',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='person_table',
            name='rollNumber',
            field=models.CharField(max_length=255),
        ),
    ]
