# Generated by Django 4.2.3 on 2023-08-13 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_remove_person_table_isstudent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person_table',
            name='course_list_created',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='person_table',
            name='courses_list',
            field=models.TextField(default='[]'),
        ),
    ]
