# Generated by Django 3.2.16 on 2023-12-16 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_remove_attendance_record_table_course_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_table',
            name='teacher',
            field=models.TextField(),
        ),
    ]
