# Generated by Django 3.2.16 on 2023-12-16 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_alter_course_table_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='person_table',
            name='course_list_created',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='person_table',
            name='courses_list',
            field=models.TextField(default='[]'),
        ),
        migrations.RemoveField(
            model_name='course_table',
            name='students_list',
        ),
        migrations.AddField(
            model_name='course_table',
            name='students_list',
            field=models.TextField(default='[]'),
        ),
    ]
