# Generated by Django 3.2.16 on 2023-12-16 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_auto_20231216_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_table',
            name='students_list',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='person_table',
            name='course_list_created',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='person_table',
            name='courses_list',
            field=models.TextField(default=None),
        ),
    ]
