# Generated by Django 3.2.16 on 2023-12-19 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_auto_20231216_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session_record_table',
            name='course_name',
            field=models.CharField(max_length=50),
        ),
    ]
