# Generated by Django 3.2.16 on 2023-12-22 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_alter_session_record_table_course_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session_record_table',
            name='location',
        ),
        migrations.AddField(
            model_name='session_record_table',
            name='lat',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='session_record_table',
            name='lon',
            field=models.FloatField(default=None),
        ),
    ]
