# Generated by Django 3.2.21 on 2023-12-27 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_auto_20231222_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance_record_table',
            name='session',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='attendance_record_table',
            name='student_Id',
            field=models.CharField(max_length=255),
        ),
    ]
