# Generated by Django 3.2.21 on 2023-12-29 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0014_admin_accounts_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='admin_accounts_table',
        ),
    ]
