# Generated by Django 4.2.7 on 2024-01-11 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0015_delete_admin_accounts_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session_record_table',
            old_name='check',
            new_name='presence',
        ),
    ]
